name: CI - Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses:   azure-prep/roboshop-github-actions/.github/workflows/ci-dev.yml@main
    with:
      appType: 'Nodejs'
      appName: 'cart'
      appTag: '280731795f58955cd1b6fe6ce5c3ac63bf502019'
    secrets:
      vault_token: ${{ secrets.TOKEN }}