name: CI - Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Dev_Deploy:
    uses: azure-prep/roboshop-github-actions/.github/workflows/aks-deploy.yaml@main
    with:
      resource_group_name: 'ukwest-dev'
      appEnv: 'dev-dev'
      appName: 'cart'
      appTag: '280731795f58955cd1b6fe6ce5c3ac63bf502019'
    secrets:
      vault_token: ${{ secrets.TOKEN }}
